#!/bin/sh

base_image_tarball=out/eve-20180309.txz
eve_tarball=/tmp/eVe.tgz

unit=0

image=eve-headless-bbk

if [ $(id -u) -ne 0 ]; then
	echo "$0 must be run as root"
	exit 1
fi

if [ -f $image ]; then
	echo "File exists: $image" >&2
	exit 1
fi

set -ex

truncate -s 800M $image

ggatel create -u $unit $image

gpart create -s MBR ggate${unit}
gpart add -a 63 -b 63 -t '!12' -s 2M ggate${unit}
gpart add -a 512k -t freebsd ggate${unit}

gpart set -a active -i 1 ggate${unit}

newfs_msdos -F 12 /dev/ggate${unit}s1

gpart create -s BSD ggate${unit}s2
gpart add -t freebsd-ufs -a 64k ggate${unit}s2

newfs /dev/ggate${unit}s2a



target=$(mktemp -d)

mount /dev/ggate${unit}s2a $target

tar xf "${base_image_tarball}" -C $target

mount_msdosfs /dev/ggate${unit}s1 $target/mnt
cp /usr/local/share/u-boot/u-boot-beaglebone/MLO $target/mnt
cp /usr/local/share/u-boot/u-boot-beaglebone/u-boot.img $target/mnt
cp $target/boot/ubldr $target/mnt
cp $target/boot/ubldr.bin $target/mnt
umount $target/mnt

cp /usr/local/bin/qemu-arm-static $target/usr/local/bin
chroot $target /usr/sbin/pw user add freebsd
mkdir -p $target/home/freebsd
tar zxf "${eve_tarball}" -C $target/home/freebsd
chroot $target /usr/sbin/chown -R freebsd:freebsd /home/freebsd

mount -t devfs devfs $target/dev
chroot $target /usr/bin/su - freebsd -c 'sh -c "cd /home/freebsd/eVe && bundle install --without electron rhodes development --deployment"'
umount $target/dev

rm $target/usr/local/bin/qemu-arm-static

umount $target

ggatel destroy -u $unit
