#!/bin/sh
#
# PROVIDE: atome
# REQUIRE: DAEMON
#
# Add the following lines to /etc/rc.conf to run atome:
#
# atome_enable (bool):	Set it to "YES" to enable atome.
#			Default is "NO".
#

. /etc/rc.subr

name="atome"
rcvar=`set_rcvar`

load_rc_config ${name}

: ${atome_enable="NO"}
atome_user="freebsd"
atome_chdir="/home/freebsd/atome"

pidfile="/tmp/${name}.pid"
command=/usr/sbin/daemon
command_args="-f -P ${pidfile} /usr/local/bin/bundle exec rake run::server"

export HOME=/home/freebsd
export PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

run_rc_command "$1"
